### ISSUE TITLE
Example for Fragment Stack

### ISSUE THREAD

**Issue by rodriigomedeiros** [vestrel00/android-dagger-butterknife-mvp#53]
Using this "framework", how do I add fragments in the stack? Example: onClick in Fragment1 open Fragment2; onClick in Fragment2 open Fragment3..

All datas each fragments must be supplied to an object in the Activity if possible.

**Comment by vestrel00** [comment]
@rodriigomedeiros [your question](https://github.com/google/dagger/issues/817#issuecomment-332001216) could be interpreted in 2 different ways. I'll answer them both.

1. "How to add multiple fragments in the same activity with access to objects held by the Activity? E.G. Add Fragment A, B, C and D into Activity X."

Adding multiple Fragments into an Activity is shown in [`example_2`](https://github.com/vestrel00/android-dagger-butterknife-mvp/tree/a.9-refactor-to-contributesandroidinjector/app/src/main/java/com/vestrel00/daggerbutterknifemvp/ui/example_2). The example shows how to add 2 fragments in the same activity in the [Activity's `onCreate`](https://github.com/vestrel00/android-dagger-butterknife-mvp/blob/a.9-refactor-to-contributesandroidinjector/app/src/main/java/com/vestrel00/daggerbutterknifemvp/ui/example_2/Example2Activity.java#L38).  However, you can create and add any amount of fragments in a button click event instead of in `onCreate`.

2. "How to add fragments within fragments within fragments with access to objects held by the Activity? E.G. Add fragment A into Activity X, then add Fragment B into Fragment A, then Add Fragment C into Fragment B..."

Adding Fragment A into Activity X, then adding Fragment B into Fragment A as a **child** Fragment of Fragment B is shown in [`example_3`](https://github.com/vestrel00/android-dagger-butterknife-mvp/tree/a.9-refactor-to-contributesandroidinjector/app/src/main/java/com/vestrel00/daggerbutterknifemvp/ui/example_3). The example shows how to add child Fragment B into parent Fragment A in the [parent Fragment's `onViewCreated`](https://github.com/vestrel00/android-dagger-butterknife-mvp/blob/a.9-refactor-to-contributesandroidinjector/app/src/main/java/com/vestrel00/daggerbutterknifemvp/ui/example_3/parent_fragment/Example3ParentFragment.java#L62). However, you can add a child Fragment into the parent Fragment in a button click event from the parent Fragment.

Adding another child Fragment, C, into an already child Fragment B is not supported by the structure provided in this project as I mentioned in the article;

<img width="730" alt="screen shot 2017-09-26 at 1 18 54 pm" src="https://user-images.githubusercontent.com/4332753/30876820-579d74de-a2bd-11e7-911c-ec279ab07267.png">

My "framework" only supports 2 levels of Fragments. Fragments in the Activity and child Fragments in the Fragments that are in the Activity. Another level can be supported, as I mentioned about `@PerGrandChild`. I would argue that deeper levels of Fragments within Fragments past 1 level of child Fragments is questionable. The questions that should be asked in this case are no longer in the scope of dependency injection but rather in scope of architectural design. In what scenario would require such a hierarchy? Is there a way to achieve a "flatter" structure?

#### A Quick Gist

Take a look at this gist for a quick overview of the structure: https://gist.github.com/vestrel00/64be913f954989fe52c674247e093218
